dbconfig: 
  testmysql: 
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.114.15:3306/evebook?useUnicode=true&characterEncoding=UTF-8
    username: bookuser
    password: 11.22.X
    
  oamysql: 
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.8:2506/oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123.abc.X
    
  oasqlserver: 
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=OA20160401
    username: OA20151231
    password: hg123.XX
    
  dyysqlserver: 
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=dywDB20160114
    username: OA20151231
    password: hg123.XX
    
  alidatasqlserver: 
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=alidata
    username: OA20151231
    password: hg123.XX
    
  oapg: 
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.8:21532/sixioa
    username: testuser1
    password: 123456X
    
  cwpg: 
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.8:21532/sixicw
    username: testuser1
    password: 123456X
  
