dbconfig:
  oasqlserver: 
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.79:1433;DatabaseName=OA20160401
    username: OA20151231
    password: hg123.XX
    
  oapg: 
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.8:21532/sixioa
    username: testuser1
    password: 123456X
    
  cwpg: 
    driver: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.8:21532/sixicw
    username: testuser1
    password: 123456X
  
